name: Deploy to K8s

on:
  workflow_dispatch:
  push:

env:
  KUBECONFIG: "kubeconfig.yml"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBECONFIG }}" >> kubeconfig.yml
        chmod og-rw kubeconfig.yml
    - name: Create secret
      run: |
        kubectl create secret generic regcred \
          --from-file=.dockerconfigjson=.docker/config.json> \
          --type=kubernetes.io/dockerconfigjson
    - name: 'Deploy'
      run: helm upgrade hello ./helm --install --force --kubeconfig kubeconfig.yml
