name: Deploy to K8s

on:
  workflow_dispatch:
  push:

env:
  KUBECONFIG: "kubeconfig.yml"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBECONFIG }}" >> kubeconfig.yml
        chmod og-rw kubeconfig.yml
    - name: Add registry
      run: helm registry login -u ${{ secrets.GITHUB_TOKEN }} ghcr.io
    - name: 'Deploy'
      run: helm upgrade hello ./helm --install --force --kubeconfig kubeconfig.yml
