name: Deploy to K8s

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./hello
    steps:
    - uses: actions/checkout@v3
    - name: Configure kubectl
      run: |
        mkdir .kube
        echo ${{ secrets.KUBECONIFG }} > .kube/config
    - name: Print
      run: kubectl get nodes
    # - name: 'Deploy'
    #   run: helm upgrade hello ./helm --install
