name: Deploy to K8s

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBECONFIG_FILE_CONTENT }}
    - run: kubectl delete secret regcred --ignore-not-found=true
    - run: kubectl create secret docker-registry regcred \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ secrets.GITHUB_TOKEN }}
    - name: 'Deploy'
      uses: WyriHaximus/github-action-helm3@v2
      with:
        kubeconfig: ${{ secrets.KUBECONFIG_FILE_CONTENT }}
        exec: helm upgrade hello ./helm --install --force
