name: Deploy to K8s

on:
  workflow_dispatch:
  push:


jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./hello
    steps:
    - uses: actions/checkout@v3
    - name: Configure kubectl
      run: |
        echo ${{ secrets.KUBECONIFG }} > kubeconfig.yml
        export $KUBECONFIG="kubeconfig.yml"
    - name: 'Deploy'
      run: helm upgrade hello ./helm --install 
