name: Deploy to K8s

on:
  workflow_dispatch:
  push:

env:
  KUBECONFIG: "kubeconfig.yml"

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./hello
    steps:
    - uses: actions/checkout@v3
    - name: Configure kubectl
      run: |
        echo ${{ secrets.KUBECONIFG }} > kubeconfig.yml
    - name: env
      run: helm env
    - name: 'Deploy'
      run: helm upgrade hello ./helm --install --kubeconfig kubeconfig.yml
