name: Deploy to K8s

on:
  workflow_dispatch:
  push:

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create secret
      run: |
        kubectl delete secret regcred --ignore-not-found=true
        kubectl create secret docker-registry regcred \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ secrets.GITHUB_TOKEN }}
    - name: 'Deploy'
      run: helm upgrade hello ./helm --install --force --kubeconfig kubeconfig.yml
