name: Workflow

on:
  push:
    paths-ignore:
    - 'helm/**'
    - '**/k8s-deployment.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hello
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build container
      run: docker build -t ghcr.io/caimito/hello:latest .
    - name: Push container
      run: docker push --all-tags ghcr.io/caimito/hello
